export enum ActionType {
  SET_SECTIONS_LIST = 'SET_SECTIONS_LIST',
  SET_SECTION = 'SET_SECTION',
  SET_STORIES_LIST = 'SET_STORIES_LIST',
  SET_KEYWORDS_LIST = 'SET_KEYWORDS_LIST',
  SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION',
  SET_SELECTED_KEYWORD = 'SET_SELECTED_KEYWORD',
  FILTER_STORIES = 'FILTER_STORIES',
}
